import './globals.css';
import './index.css';
// import './scss/base/__index.scss'
import { Lato } from 'next/font/google';
import Navigation from "../components/layouts/Navigation";
import Footer from '../components/layouts/Footer';

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
};

const lato = Lato({
  subsets: ['latin'],
  weight: ['400', '700'],
  variable: '--font-lato',
});

export default async function RootLayout({ children }) {
    const res = await fetch(`${process.env.NEXT_PUBLIC_WORDPRESS_API_BASE_URL}/graphql`, {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
            query: `
                query {
                    siteLogo
                }
            `,
        }),
    });

    const result = await res.json();
    const siteLogo = result.data?.siteLogo || null;

    return (
        <html lang="en">
            <body className={lato.variable}>
                <Navigation siteLogo={siteLogo} />
                    {children}
                <Footer />
            </body>
        </html>
    );
}
